
version: '3.8'

services:
  backend:
    container_name: flask-backend
    build: ./backend
    image: laarcx/flask-backend:latest
    ports:
    - "5000:5000"
    restart: unless-stopped
    

  frontend:
    build: ./frontend
    image: laarcx/nginx-frontend:latest
    ports: 
    - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped